### ISSUE TITLE
Object Labels - Add Referral... to start

### ISSUE THREAD

**Issue by bradstruss** [Salesforce-org-Impact-Labs/01HousingandHomelessness#149]
To avoid admin/user confusion, we'd discussed having the object labels start with "Referral..."

For example, the label for refrec__Service__c object is Service. This is the same label as PMM's pmdm__Service__c object.   

I suggest labels be:
Referral Client Profile
Referral Open Hours
Referral Service
Referral Service Exclusion

**Comment by endlesscurls** [comment]
agree, thanks brad! cc: @mshanemc
