### ISSUE TITLE
Service Match - Get Recommended Services without completing Client Profile Builder

### ISSUE THREAD

**Issue by szeitz** [Salesforce-org-Impact-Labs/01HousingandHomelessness#252]
In order to be able to quickly find available services for my client, 
I should be able to select 'Get Recommended Services' on the contact page and see services without completing the Client Profile Builder.

Requirements:
1) Selecting 'Get Recommended Services' should return available services within the distance range for the client information that currently exists
2) Completing the profile builder should improve the search results

**Comment by szeitz** [comment]
What needs to be on the contact record in order for services to be returned with 'get recommendation'?

**Comment by ShashiChettepu** [comment]
closing - https://github.com/Salesforce-org-Impact-Labs/01HousingandHomelessness/pull/282
