### ISSUE TITLE
Remove Print from referral menu

### ISSUE THREAD

**Issue by szeitz** [Salesforce-org-Impact-Labs/01HousingandHomelessness#274]
In order to limit print functionality to one location,
As a user,
I would like the 'print' option removed from the referral screen in Service Match.

AC
When a user selects the referral button for a service, the next screen should only have two options - email and SMS (image 1)
The only location a user can 'print' a service from will be the main service page (image 2)

Image 1
![2021-06-04_16-02-42](https://user-images.githubusercontent.com/28901633/120862413-825a2980-c54e-11eb-925e-ce61e2788f86.gif)

Image 2
![2021-06-04_16-02-32](https://user-images.githubusercontent.com/28901633/120862441-92720900-c54e-11eb-97fc-214b07a6e0de.gif)

**Comment by ShashiChettepu** [comment]
closing - fixed : https://github.com/Salesforce-org-Impact-Labs/01HousingandHomelessness/commit/3c5c1de53c4f5a0810c8d3f7aa9038ebb7b51bc1
